tensor_core_home:
    path:     /home/{_subpage}
    defaults: { _controller: TensorCoreBundle:Landing:landing }
    requirements:
        _subpage: \d+

tensor_core_home_expanded:
    path:     /home/{_subpage}/athlete/{_athlete}
    defaults: { _controller: TensorCoreBundle:Landing:landing }
    requirements:
        _subpage: \d+
        _athlete: \d+


tensor_core_api:
    path:     /api
    defaults: { _controller: TensorCoreBundle:Api:index }

tensor_core_api_init:
    path:     /api/init
    defaults: { _controller: TensorCoreBundle:Api:default }

tensor_core_about:
    path:     /about
    defaults: { _controller: TensorCoreBundle:Static:about }
#tensor_core_about_locale:
#    path:     /{_locale}/about
#    defaults: { _controller: TensorCoreBundle:Static:about }
#    requirements:
#        _locale: '%app.locales%'
