security:
    providers:
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|src|css|images|js)/
            security: false
        main:
            anonymous: ~
