services:
    last_login_listener:
        class:        Tensor\UserBundle\Listener\LastLoginListener
        arguments:    ['@doctrine.orm.entity_manager']
#        autowire: true
        tags:
            - { name: kernel.event_subscriber, event: security.interactive_login, method: onAuthenticationSuccess }

